### ISSUE TITLE
Importing to lazy-loaded module

### ISSUE THREAD

**Issue by oijoijoi** [JustCommunication-ru/ngx-splide#1]
Had found such an issue: 
Trying to use that package in lazy-loaded module, error occurred: 
"BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead."
Changing "BrowserModule" to "CommonModule" fixed that.
I suppose it could be useful to make that change in common package.
Thx.

**Comment by wiistriker** [comment]
Just pushed v0.0.13 to npm, please check

**Comment by oijoijoi** [comment]
Checked, thats is, thx.
