### ISSUE TITLE
How do I use the sync function?

### ISSUE THREAD

**Issue by michitosh** [JustCommunication-ru/ngx-splide#2]
How to use the sync functionality?
https://splidejs.com/guides/apis/#sync

Currently I have two Splide Sliders that need to be synced - one big with fullscreen images and one small with thumbnails used as navigation. 

`<splide 
    (onInit)="onMainSplideInit($event)"  
    class="splide mainSlider" [options]="{type: 'slide',pagination: false,arrows: false,drag: true,lazyLoad: 'nearby',preloadPages: 3}">
    <splide-slide *ngFor="let media of data.media">
      <div>
        // big img
      </div>
    </splide-slide>
  </splide>
  <splide 
    (onInit)="onSecondarySplideInit($event)"    
    class="splide secondarySlider" [options]="{ rewind: true, isNavigation: true, gap: 5, focus: 'center', pagination: false, cover: true, lazyLoad: 'nearby', preloadPages: 20, fixedWidth: 60, fixedHeight: 60 }">
    <splide-slide *ngFor="let media of data.media">
      <div>
        //thumbnail
      </div>
    </splide-slide>
  </splide>`

and in the inInit functions i tried to sync them:

`onMainSplideInit = (splide) => {
    this.mainSplide = splide;
  }

  onSecondarySplideInit = (splide) => {
    this.secondarySplide = splide;

    this.mainSplide.sync(this.secondarySplide).mount();
  }`
  
  
this works partial - when I move the mainSlider the secondarySlider moves too, but not in the other direction...

Is there a proper way to implement this?

**Comment by wiistriker** [comment]
I just released 0.0.15 version of the package. Please update and take a look

https://github.com/JustCommunication-ru/ngx-splide#sync

**Comment by michitosh** [comment]
Thank you @wiistriker! Works perfectly!
