### ISSUE TITLE
Angular Ivy Support

### ISSUE THREAD

**Issue by abhishekcpwebline** [JustCommunication-ru/ngx-splide#7]
Hello @wiistriker - Thanks for the great library. I am using this library and everything works as expected. Although, you can add support for Ivy in this library as it gives a warning while we do ng serve after installing this library.

Looking forward to it.

Thanks.

**Comment by wiistriker** [comment]
Hello! I will take a look on this week. Thanks!

**Comment by abhishekcpwebline** [comment]
Thanks @wiistriker. Also, autoHeight property is not working in the options. Could you check it as well ?

**Comment by wiistriker** [comment]
Please paste warning text you got after running ng serve

**Comment by abhishekcpwebline** [comment]
hi @wiistriker - Here is the message I am getting,

**_Encourage the library authors to publish an Ivy distribution_**

**Comment by wiistriker** [comment]
Please check 2.0.0 version of the library.

Angular version was updated to 12 and library was compiled with ivy now.
Splide version was bumped to 4 and autoHeight seems to work now (you can check demo https://justcommunication-ru.github.io/ngx-splide/ Vertical example)

**Comment by wiistriker** [comment]
Do you have [syncWith] on #mainSplide? If so remove it and try again.

Angular behaviour changed so i write some information about sync:
https://github.com/JustCommunication-ru/ngx-splide#sync

**Comment by abhishekcpwebline** [comment]
Thanks, @wiistriker , After removing [syncWith] from mainSplide, the error has been gone and it's working fine.

However, my content is still not auto-adjusting even though I have written autoHeight as true in sliderOptions.

Not sure, what I am missing. Below is the configuration code for sliderOptions.

`sliderOptions = {
    // Add your options here
    arrows : false,
    autoHeight:true
  };`

**Comment by wiistriker** [comment]
i try with options from documentation and it working:

<splide [options]="{
                    type      : 'loop',
                    direction : 'ttb',
                    height    : '20rem',
                    focus     : 'center',
                    autoHeight: true
                }">

**Comment by abhishekcpwebline** [comment]
@wiistriker - For me it is still not working, I have written the below code in my HTML.

`<splide [options]="{arrow : false, autoHeight:true}" [syncWith]="mainSplide">
          <splide-slide *ngFor="let tab of leadershipTabs; let index = index">
          </splide>`
          
          However, it is still keeping the extra space in my content. Below is the screenshot.
          
          
![image](https://user-images.githubusercontent.com/107850651/236181315-4590aec6-6478-40af-a131-b398a53821b7.png)
![image](https://user-images.githubusercontent.com/107850651/236181451-19dd727e-f4b8-4003-8961-9a9c8e14e3eb.png)

**Comment by wiistriker** [comment]
Looks like splidejs issue.

Try to add height for the each slide

```
              <splide [options]="{
                    type      : 'loop',
                    direction : 'ttb',
                    height    : '20rem',
                    focus     : 'center',
                    autoHeight: true
                }">
                    <splide-slide *ngFor="let image of images">
                        <div style="height: 20rem;">
                            <img [src]="image.src" alt="" />
                        </div>
                    </splide-slide>
                </splide>
```

**Comment by abhishekcpwebline** [comment]
@wiistriker - tried your solution of height, but now the content is getting cut by applying the height.

![image](https://user-images.githubusercontent.com/107850651/236397480-47cf85a2-9e9e-423e-96a3-7550f9d34e35.png)
