### ISSUE TITLE
Autoplay option not working

### ISSUE THREAD

**Issue by droidcaptcha** [JustCommunication-ru/ngx-splide#8]
Unable to get Autoplay working in options when using NGX-splide, official docs state autoplay: true as the option to use.

**Comment by wiistriker** [comment]
Just checked autoplay option and it seems working as expected

Please take a look demo at https://justcommunication-ru.github.io/ngx-splide/

![Снимок экрана 2024-10-18 в 16 53 19](https://github.com/user-attachments/assets/88dca1d3-2545-4384-8a33-e2b9cbbfbe6a)

**Comment by droidcaptcha** [comment]
May I ask what browser/OS you are using? I can confirm your demo works on Mac OS Safari/Chrome but not on Windows

**Comment by wiistriker** [comment]
Trying on Windows Chrome and MacOS Chrome/Firefox/Safari

**Comment by wiistriker** [comment]
I will close this issue. Please feel free to reopen it when you will be able to reproduce the issue. You can use stackblitz for this
